# docs: https://rust-lang.github.io/rustfmt
format_code_in_doc_comments = true               # nightly feature
group_imports               = "StdExternalCrate" # nightly feature
imports_granularity         = "Crate"            # nightly feature
match_block_trailing_comma  = true
max_width                   = 100
use_small_heuristics        = "off"
