name: Wasm

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Check for errors
        run: just rust-check
        env:
          RUST_BACKTRACE: 1
